openapi: 3.0.0
info:
  title: E-Com API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: Local development server    

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                password:
                  type: string
                userType:
                  $ref: '#/components/schemas/UserType'
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request, invalid user data provided

  /auth/login:
    post:
      summary: Authenticate user
      description: Authenticate a user by providing credentials.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
              example:
                token: your-auth-token
        '401':
          description: Unauthorized
        '404':
          description: Invalid email or password